### ISSUE TITLE
Problema con Fargo VOD

### ISSUE THREAD

**Issue by colmo** [Paco8/plugin.video.movistarplus#23]
Buenas tardes,
Lo primero gracias por tu trabajo y tu tiempo! 

Estoy teniendo problemas con el plugin y la serie Fargo. Al intentar entrar en la "Temporada 5" (La única que hay disponible). Aparece un mensaje de error en rojo que dice "Movistar+ Error" . Con el resto de contenidos no tengo ningún problema. Desde la app oficial se reproduce correctamente.

Te adjunto el log.
Gracias!!

> 2023-12-04 18:10:24.852 T:10616   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'UrlVideo'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Olmo\AppData\Roaming\Kodi\addons\plugin.video.movistarplus\default.py", line 7, in <module>
                                                       run()
                                                     File "C:\Users\Olmo\AppData\Roaming\Kodi\addons\plugin.video.movistarplus\resources\lib\plugin.py", line 755, in run
                                                       router(params)
                                                     File "C:\Users\Olmo\AppData\Roaming\Kodi\addons\plugin.video.movistarplus\resources\lib\plugin.py", line 695, in router
                                                       add_videos(params['name'], 'episodes', m.get_episodes(params['id']))
                                                     File "C:\Users\Olmo\AppData\Roaming\Kodi\addons\plugin.video.movistarplus\resources\lib\movistar.py", line 906, in get_episodes
                                                       t['url'] = video['UrlVideo']
                                                   KeyError: 'UrlVideo'
                                                   -->End of Python script error report<--                                                   
2023-12-04 18:10:24.942 T:4520    error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.movistarplus/?action=season&id=3048884&name=Temporada%205
2023-12-04 18:10:24.943 T:8848    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.movistarplus/?action=season&id=3048884&name=Temporada%205) failed
2023-12-04 18:10:25.590 T:13116 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.

**Comment by colmo** [comment]
Confirmo que está solucionado.
Gracias!
