### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by pepebc** [Paco8/plugin.video.movistarplus#32]
SO  Linux EndeavourOS
Kodi 20.4.0
Python 3.11.7
plugin.video.movistarplus-0.8.11.zip
script.module.ttml2ssa-0.3.8.zip

_2024-02-13 12:43:50.808 T:17721   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'str' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "/home/pepe/.kodi/addons/plugin.video.movistarplus/default.py", line 7, in <module>
                                                       run()
                                                     File "/home/pepe/.kodi/addons/plugin.video.movistarplus/resources/lib/plugin.py", line 760, in run
                                                       router(params)
                                                     File "/home/pepe/.kodi/addons/plugin.video.movistarplus/resources/lib/plugin.py", line 655, in router
                                                       play(params)
                                                     File "/home/pepe/.kodi/addons/plugin.video.movistarplus/resources/lib/plugin.py", line 111, in play
                                                       cdn_token = m.get_cdntoken()
                                                                   ^^^^^^^^^^^^^^^^
                                                     File "/home/pepe/.kodi/addons/plugin.video.movistarplus/resources/lib/movistar.py", line 396, in get_cdntoken
                                                       return data.get('access_token')
                                                              ^^^^^^^^
                                                   AttributeError: 'str' object has no attribute 'get'
                                                   -->End of Python script error report<--_

**Comment by Paco8** [comment]
A mí me funciona. Quizás haya sido un fallo temporal del servidor. Prueba otra vez.

**Comment by pepebc** [comment]
Efectívamente, hoy vuelve a funcionar correctamente. Pensaba que podía ser alguna incompatibilidad con la versión de Python. Gracias, exelente addon.
